name: Bump version
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: New tag to create

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.tag }}
